version: '3.9'
services:
  cookbook-backend:
    image: cookbook-backend
    ports:
      - "8081:8090"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 632gz-R
      POSTGRES_USER: postgres
      POSTGRES_DB: CookbookApplication


